# Variables 
CC = gcc
CFLAGS = -Wall -ansi -pedantic

# Target and Dependencies 
remove_blanks: remove_blanks.c
	$(CC) $(CFLAGS) remove_blanks.c -o remove_blanks

# Clean target 
clean:
	rm -f remove_blanks